//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_p
    {
        public int id_ppro { get; set; }
        public string nom_ppro { get; set; }
        public Nullable<double> pt_ppro { get; set; }
        public Nullable<double> p_ppro { get; set; }
        public Nullable<double> g_ppro { get; set; }
        public Nullable<System.DateTime> date_ppro { get; set; }
    }
}
