//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_m
    {
        public int id_mpro { get; set; }
        public string nomp_mpro { get; set; }
        public string nom_mpro { get; set; }
        public Nullable<double> prix_mpro { get; set; }
        public Nullable<System.DateTime> date_mpro { get; set; }
    }
}
