//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_info
    {
        public int id_proi { get; set; }
        public string pro_nom { get; set; }
        public Nullable<System.DateTime> pro_date { get; set; }
        public Nullable<double> pro_price { get; set; }
    }
}
