//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int id_pur { get; set; }
        public Nullable<int> id_cat { get; set; }
        public Nullable<int> id_four { get; set; }
        public string Désignation { get; set; }
        public string Unité { get; set; }
        public string Catégorie { get; set; }
        public string Fournisseur { get; set; }
        public Nullable<double> Prix_U_H_T { get; set; }
        public Nullable<double> T_V_A { get; set; }
        public Nullable<double> Poids { get; set; }
        public Nullable<double> Quantité { get; set; }
        public Nullable<double> Total_H_T { get; set; }
        public Nullable<double> Total_T_V_A { get; set; }
        public Nullable<double> Total_T_C { get; set; }
    
        public virtual Catégorie Catégorie1 { get; set; }
        public virtual Fournisseurs Fournisseurs { get; set; }
    }
}
