//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salaire
    {
        public int id_salaire { get; set; }
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string num_tel { get; set; }
        public string CIN { get; set; }
        public string Département { get; set; }
        public byte[] image_emp { get; set; }
        public string Type { get; set; }
        public Nullable<double> Salaire1 { get; set; }
        public Nullable<double> Prix_h { get; set; }
        public Nullable<double> nbr_h { get; set; }
    }
}
