//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAIM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDAIMEntities : DbContext
    {
        public SDAIMEntities()
            : base("name=SDAIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catégorie> Catégorie { get; set; }
        public virtual DbSet<Fournisseurs> Fournisseurs { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<Employés> Employés { get; set; }
        public virtual DbSet<Salaire> Salaire { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Project_info> Project_info { get; set; }
        public virtual DbSet<project_p> project_p { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<Project_m> Project_m { get; set; }
    }
}
